### ISSUE TITLE
버그있습니다

### ISSUE THREAD

**Issue by YunJH** [devconcert/Telegram#21]
말로설명이될지모르겠네요ㅠㅠ
1.말을쓰던중사진공유를하려고공유버튼을누른다(자판이올라와있는상태)
2.공유-사진촬영 을누르면 어떤카메라앱을쓸껀지 고그라고 목록이뜬다
3.그냥사진공유안해야지하고 2번상태에서 뒤로가기 버튼을 누른다 
4.비밀번호입력화면이갑자기뜬다

무슨말인지아시겠나용...?ㅠㅠ
갤러리를선택했어야됐는데사진촬영을잘못눌러서 다시하려고뒤로가기눌렀더니 비번치는창이뜨더라고요..ㅠ
아직적응이안되서계속이실수하는데 그설때아다비번계속치려니불편하네요..ㅠ

**Comment by devconcert** [comment]
@YunJH 안녕하세요~!

피드백 감사합니다. 무슨 말씀인지 이해했습니다.~~
제가 확인해보고 피드백 드릴게요.

불편하게 해드려서 죄송합니다. 공식앱에는 없는 비밀번호 기능을 급하게 넣느라, 아직 버그가 남아있네요.
피드백 정말 감사합니다. :+1:

**Comment by YunJH** [comment]
저 하나더 말씀드릴게요!!비밀대화할때원래알람이좀늦게오나요??? 제가남자친구랑쓰고있는데 알람이거의적게는2분에서20분정도 늦게오는데 폰이이상한건지 어플의문젠지모르겠네요@.@ 전g2쓰고있습니다!

**Comment by devconcert** [comment]
@YunJH 혹시 사용하실때, 앱을 강제 종료하시나요?

**Comment by YunJH** [comment]
아뇨ㅠㅠ 가끔메모리정리를하긴하는데 그거말고는강제종료는안합니다ㅠㅠ

**Comment by devconcert** [comment]
@YunJh 원인을 알겠습니다. 
자주 앱 업그레이드 한다는 피드백이있어 몇일뒤에 업데이트 진행할게요!!

**Comment by YunJH** [comment]
오왕 감사합니다!! 기다릴게요ㅎㅎ

**Comment by devconcert** [comment]
1.9.11 버전 업데이트 완료했어요.~~
사용해보시고 피드백 부탁드려요^^

안드로이드 마켓에는 반영이 조금 느릴수 있어요
설정->마지막 하단부분 1.9.11 버전을 확인해 주세요~

**Comment by devconcert** [comment]
Release 1.9.10 ~ 1.9.11 에 적용완료

**Comment by YunJH** [comment]
이제 알람 잘 울려요~!!ㅎㅎㅎ 빠른해결감사합니다ㅎㅎ

**Comment by devconcert** [comment]
@YunJH 다행네요! 다른 피드백 있으면 언제든 남겨주세요~

**Comment by devconcert** [comment]
이슈  close합니다
