### ISSUE TITLE
기능추가 - 다운로드 경로

### ISSUE THREAD

**Issue by SonYonghun** [devconcert/Telegram#24]
다운로드 경로 사진, 동영상, 문서 등 다운로드 경로를 내장메모리로 할지 외장메모리로 할지 선택할수 있는 설정이 필요해요.

**Comment by devconcert** [comment]
@SonYonghun 안녕하세요. 피드백 감사합니다. github가입하셔서 글남겨주셨네요. 피드백 주신 기능 검토해 보겠습니다. :+1:

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#24
