### ISSUE TITLE
사생활 보호 기능 관련 의견

### ISSUE THREAD

**Issue by digitie** [devconcert/Telegram#38]
무슨 이유에서인지는 모르겠지만 안드로이드용 텔레그램 앱은 자체적으로 sqlite3를 포함하고 있네요. JNI로 API까지 만든거 보면 속도 때문인건 것 같기도 하고 사생활 보호 때문인 것 같기도 합니다.

이왕 sqlite3를 내장할꺼면 https://github.com/sqlcipher/android-database-sqlcipher 를 도입해서 아예 저장되는 메세지 자체를 암호화하는게 어떨까 싶습니다. 라이센스는 큰 문제가 없을 듯 하구요.

secretkey 가 문제인데...
1. vpn 처럼 잠금화면이나 비밀번호가 추가된 경우 
ics부터 도입된 keychain을 활용하여 이로부터 secretkey를 얻어내서 암호화하면 좋지 않을까 싶습니다. 
2. 사용자가 안드로이드에서 보안을 활성화하지 않은 경우
휴대전화번호 내지는 telephony.getDeviceId() 로 고유번호를 얻어서 secretkey로 쓰면 되지 않을까 싶구요.

액션바를 자체적으로 만들어쓰는 것 부터 시작해서 텔레그램은 소스를 뜯어볼수록 러시아의 패기가 느껴지는듯 합니다. 고생 많으십니다.

그리고 자잘한 기능들은 업스트림에도 pull request 해보세요. 한국사람만 혜택을 보기에는 아깝습니다.

**Comment by devconcert** [comment]
@digitie 안녕하세요. 소중한 피드백 감사드립니다.^^
저희도 작업을 진행하면서 메인 브렌치에 반영을 생각하고 있습니다.
오리지널의 코드의 경우 오너십이 텔레그램 측에 있으니, 코드 정리하면서 반영해 볼게요
그리고, 피드백 주신 내용도 검토하도록 하겠습니다.

https://github.com/sqlcipher/android-database-sqlcipher/ 이녀석은 라이센스가 문제가 없겠네요(감사합니다)

```
License

The Android support libraries are licensed under Apache 2.0, 
in line with the Android OS code on which they are based. 
The SQLCipher code itself is licensed under a BSD-style license from Zetetic LLC. 
Finally, the original SQLite code itself is in the public domain.
```

감사드립니다. ^^

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#38
