### ISSUE TITLE
설정의 알림 및 소리

### ISSUE THREAD

**Issue by mistarry09** [devconcert/Telegram#40]
안녕하세요^^ 잘사용하고 있습니다.

버그인지 모르겠지만 설정-알림 및 소리-메시지 알림 에서 메시지 미리보기를 off하여도

알림 팝업에서는 미리보기가 표시됩니다.(메세지 내용이 나옴)

pc버전이나 아이패드에서 미리보기를 off하면 푸시알림에서는 메세지왔다는것만 나오고 내용은 나오지 않습니다.

안드로이드만 버그인것 같습니다.

답변 부탁드려요^^

**Comment by skyorbit** [comment]
JUST NOTE: In 'SettingsNotificationActivity', It's likely that function updateServerNotificationsSettings is temporarily disabled due to works for update. Kind of setting integration. Need to keep tracking and should do rebase.

**Comment by devconcert** [comment]
@mistarry09  안녕하세요. 매인스트림과 동일한 버그로 보이네요! 관련내용 조만간 수정반영할게요~!!
피드백 감사합니다.

**Comment by devconcert** [comment]
#72

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#40
