### ISSUE TITLE
Contact display order 버그.

### ISSUE THREAD

**Issue by devconcert** [devconcert/Telegram#41]
1.9.13에 수정 반영예정

**Comment by devconcert** [comment]
https://github.com/devconcert/Telegram/commit/612487fe76c5adce8d8fafd98639ae90ed10fcc5 #41 버그수정

**Comment by FoxSays** [comment]
차후에는 설정으로서 적용되게 하는것도 괜찮을거 같네요. 성, 이름으로 갈지 이름, 성으로 갈지...

**Comment by devconcert** [comment]
@FoxSays 좋은 생각입니다. 현재는 한국어인 경우에만 성 이름으로 표시되게 하였고, 다른 나라인경우는 이름 성으로 표시됩니다.

**Comment by FoxSays** [comment]
@devconcert  프로그램 설정언어에 따라 간다는 말씀이시죠? 제 경우, 그 설정은 영어로 해 놓고 있어서 이게 적용된걸 못 본 모양이네요 ^^

**Comment by devconcert** [comment]
@FoxSays
현재 +82(South Korea)로 인증을 한경우
앱 언어설정에서 한국어로 한경우에만

이름 성 
성 이름

순서를 변경하게 했습니다

**Comment by FoxSays** [comment]
@devconcert 전 둘다 해당이 안되네요 ㅋ 어느쪽이던 명확히 옵션이 있는쪽이 좋을거 같습니다

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#41
