### ISSUE TITLE
웹 이미지 검색의 추가

### ISSUE THREAD

**Issue by FoxSays** [devconcert/Telegram#42]
iOS 텔레그램에서 매우 유용하게 쓰고 있는 기능인데 안드로이드는 이걸 지원을 안하네요. 웹에서 이미지를 검색한 후 이걸 바로 보낼 수 있는 기능인데, 이걸 구현하면 굉장히 편할 거 같네요.

**Comment by devconcert** [comment]
@FoxSays 좋은 피드백 감사합니다.
검색기능에 대해서는 저희가 기능 추가를 고려하고 있었습니다.
사용자의 입장에서 좋은 기능이 될 듯 합니다.

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#42
