### ISSUE TITLE
스크린샷 금지를 다시 넣어 달라는 요청.

### ISSUE THREAD

**Issue by devconcert** [devconcert/Telegram#65]
구글플레이 피드백

```
스크린샷 방지 기능 이 있는 텔레그램 버전이 있다 와서 왔는데 실망이군요. 
밑에 스샷 방지 없애달라고 하는 사람도 있던데
보안 때문에 쓰는 메신저에 스샷 방지가 있으면 더 좋다고 생각되는데
굳이 스샷을 굳이 찍어서 남기고 싶으면 카톡으로 가시길 바랍니다. 
보안 앱 반푼이 만들지 마시고...
```

**Comment by FoxSays** [comment]
스크린샷 방지를 넣는 의미가 있을까 싶습니다. 

제가 알기로는 어차피 이건 클라이언트에서 처리를 할 수 밖에 없는 내용이고 (서버에서 스샷찍는지 감시가 될 리가 없으니) 결국 이 클라이언트를 쓰는 내가 스샷을 못 찍어도 상대방이 다른 클라이언트를 쓰고 있으면 얼마든지 찍을 수 있는 상황인걸로 아는데요. 오히려 상대방의 행동은 강제하지 못하고 내 행동은 제한되는 만큼 상황이 더 안좋아지는게 아닌지;;;

**Comment by devconcert** [comment]
@FoxSays 사실 이부분도 고려를 하고있어요.
메인 스트림에 적용이 되지 않은한
반쪽짜리 앱인 거죠..

나만 스크린샷이 안된다고해도 상대방이 스크린샷을 찍으면 무용지물이죠.

메인스트림에서는 스크린샷 동작을 하면 ,

대화 상대방에게 스크린샷을 찍었다는 노티를
보내지 않을까하는 작업을 하고 있는 듯 하네요

**Comment by FoxSays** [comment]
@devconcert  맞아요. 굳이 이 포크의 기능을 제한해 봤자 의미도 없고... 

메인스트림에서는 저렇게 처리할 계획이군요... 하긴 텔레그램의 컨셉상 그 이상은 힘들겠죠.

**Comment by devconcert** [comment]
메인 스트림의 시크릿 대화방에서 캡춰를 하면 상대방에서 화면 캡춰 메세지를 전송하지만,
1) 텔톡에서는 화면캡춰를 하면 화면캡춰한 내용은 삭제,
2) 그리고 친구에게메세지는 보내지 않음.

이렇게 변경한 이유는, 텔톡을 사용할때 보안을 생각해서 사용을 하지만
상대방이 캡춰했다는 메세지를 보고 싶지 않음.

**Comment by devconcert** [comment]
시크릿 대화방에 화면캡춰 알림 적용.

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#65
