### ISSUE TITLE
최종 접속시간 관련 버그

### ISSUE THREAD

**Issue by FoxSays** [devconcert/Telegram#74]
최종접속시간이 정확하게 표시되질 않네요.

아시다시피 텔레그램의 Privacy설정에서 최종접속시간의 공개 설정이 추가되었습니다. 이걸 어떻게 설정하느냐에 따라 내가 접속시간을 공개한 유저들의 접속시간을 나도 볼 수 있도록 되어 있지요. 공식 클라이언트에서는 이렇게 작동하고 있습니다. 

하지만 현재 텔레그램 시크릿톡에서는 이 공개여부 설정과는 상관없이 모든 유저들이 비공개 설정을 해 놓은 것 처럼 (혹은 내가 전체 비공개를 설정해 놓은 것 처럼) 보여지고 있습니다. 실제로는 공개로 설정이 되어 있음에도 불구하고 말이죠. 

즉, 내 접속시간을 공개해 놓고도 남의 접속시간은 하나도 볼 수 없는 상황입니다. 이건 오류로 보이네요. 확인 부탁드립니다

**Comment by devconcert** [comment]
@FoxSays 안녕하세요. 답변이 많이 늦었네요ㅜㅜ
말씀주신 부분은 일부러 코드상에서 제가 넣어 놓은 부분입니다.(비공개 설정을 해 놓은 것 처럼 보이게)
주신 말씀을 보면서 생각드는 부분은 비공개 설정으로 보이기 때문에 사용자분들이 설정->비공개 이부분을 설정을 하지 않을 수 있다는 생각입니다.
(기존 오리지널 처럼 수정을 하고 사용자 분들께 안내를 드리는게 좋을 듯 합니다.)

좋은 의견 감사합니다.

**Comment by FoxSays** [comment]
네. 이 부분에 대해 전에도 유저들이 피드백이 많았었기에 의도적으로 그렇게 하신것이 아닌가 생각은 했었습니다만 일단 설정과 무관하게 이렇게 적용되어 결국 "나만 손해보는" 상황이 되어 버리기에 리포팅을 했습니다. ^^

유저 설정을 앱이 임의로 건드리는게 가능한지는 모르지만 만약 가능하다면 로그인시 기본 설정을 전체 비공개로 설정해버리고 (이 과정에서 개별 유저 공개를 설정한건 건드리지 말아야겠죠 - 다시 설정하자면 일이 많아지니) 그걸 유저가 다시 수정했을때 팝업 등으로 공지하는게 가장 바람직한 방법 같네요. 일반적인 유즈케이스에서 로그인은 기기 변경시 한번 정도 할 테니까요. 

만약 불가능하다면 그냥 팝업 띄워서 처음 한번 공지하는 정도가 가장 베스트긴 하겠지만요. 아무튼 피드백 드릴때마다 답변 달아주셔서 감사합니다. ^^

**Comment by FoxSays** [comment]
오늘 업데이트 되어 봤는데 이 부분은 아직 수정이 안 되었네요. 언제쯤 수정 되려나요...

**Comment by devconcert** [comment]
@FoxSays 이번주에 급한 패치가 아닌경우를 제외하고 돌아오는 일욜쯤에 패치를 할 예정입니다!!
말씀주신부분은 코드수정은 하였으나 이번 메인스트림 업데이트와 사용자 스티커 부분에 대한 업그레이드로 인해 (사용자 접속시간 버그)는 충분한 테스트가 아루어지지않아 반영은 아직 못했습니다.ㅜㅜ

**Comment by devconcert** [comment]
수정 버전 마켓에 업로드 되었습니다. 확인해 보시겠어요?

**Comment by FoxSays** [comment]
확인이 늦었네요. 최초 한번 관련기능이 제대로 수정 안 돤 듯한 모습을 보였는데 종료하고 재실행하니 수정되었습니다.

수고하셨어요  ^^

**Comment by devconcert** [comment]
@FoxSays 잘못된 부분에 대해 알려주셔서 감사합니다. ^^
