### ISSUE TITLE
기능 개선 - 기본 이모티콘 크기 변경

### ISSUE THREAD

**Issue by devconcert** [devconcert/Telegram#8]
구글 플레이 피드백

기본 이모티콘 크기 변경

**Comment by skyorbit** [comment]
it needs to be more larger.
and new emoji should be more smaller than now.

**Comment by devconcert** [comment]
기본 이모티콘 크게 변경완료.

**Comment by devconcert** [comment]
This issue was moved to telegramtalk/Telegram#8
