### ISSUE TITLE
Two-step verification 활성화시 로그인 문제

### ISSUE THREAD

**Issue by FoxSays** [devconcert/Telegram#80]
최근에 로그인시 전화번호 인증과 더불어 사용자가 지정한 패스워드를 입력해야 가능하도록 변했는데, 이게 활성화된 상태에선 텔레그램톡에서는 에러가 뜨면서 로그인을 할 수가 없더군요. 텔레그램 데탑 등을 사용해서 패스워드를 비활성화 해야 했습니다.

**Comment by devconcert** [comment]
@FoxSays 이슈 감사합니다. ㅜㅜ 관련내용 업데이트 작업은 완료하였으나, 다른 이슈가 있어서 수정중이였습니다. 수요일 밤에 업데이트 예정입니다.

**Comment by devconcert** [comment]
@FoxSays 안녕하세요 업데이트 하였습니다.!! 확인 부탁드려요~

**Comment by FoxSays** [comment]
@devconcert 네 방금 확인해 봤습니다. 정상적으로 작동하고 있어요.
